### ISSUE TITLE
Version and package source not found when generating BOM from requirements.txt

### ISSUE THREAD

**Issue by TimErdmann87** [ibm-cloud-docs/code-risk-analyzer-cli-plugin#2]
Versions:
cra 1.2.0
pip 23.0.1

Issue:
When creating the BOM from the requirements.txt generated from pip (see below) it is returned that no version for the packages is found and that the package source could not be found under the generated URL. It's unclear why no package version could be found although the version is declared in the requirements.txt and why the URL includes "%00" to separate the characters of the package name . Without the "%00"s the package source will be found using the URL.

requirements.txt
![image](https://user-images.githubusercontent.com/52191968/227682098-8e73fdf3-b18b-41b9-a8b6-d0ff94dbc8f8.png)

bash console output (same for PowerShell and cmd)
![image](https://user-images.githubusercontent.com/52191968/227682142-e11249b3-eb1d-444e-ab51-305f11062ee1.png)
![image](https://user-images.githubusercontent.com/52191968/227682195-5af54cc9-997c-4be5-a791-2f494f8976ea.png)

**Comment by DavidLopezIBM** [comment]
@TimErdmann87 Hi Tim, I have created an issue on the CRA issues board. Currently taking a look: https://github.ibm.com/oneibmcloud/CD-CRA/issues/1765
